on: [pull_request]

jobs:
  clang-tidy:
    name: runner / clang-tidy
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/arkedge/action-clang-tidy:v1
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: clang-tidy
        uses: arkedge/action-clang-tidy@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review

